# Generated by Django 5.0.9 on 2024-11-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Package', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_in_dbl', models.FloatField(verbose_name='Price Per Person in Double')),
                ('pp_in_sgl', models.FloatField(verbose_name='Price Per Person in Single')),
                ('chd_2_6', models.FloatField(verbose_name='Child 2-6 Years Rate')),
                ('chd_6_11', models.FloatField(verbose_name='Child 6-11 Years Rate')),
                ('infant_rate', models.FloatField(verbose_name='Infant Rate')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.package')),
            ],
        ),
    ]
