# Generated by Django 5.0.9 on 2024-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyConversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='source_currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='target_currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
