# Generated by Django 5.0.9 on 2024-11-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('booking_link', models.URLField()),
                ('image', models.ImageField(upload_to='hotels/')),
                ('amenities', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=15)),
                ('unavailable_dates', models.ManyToManyField(blank=True, to='Hotel.date')),
            ],
        ),
    ]
